# Generated by Django 5.0.4 on 2024-04-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('phrase_1', models.TextField(blank=True, null=True)),
                ('phrase_2', models.TextField(blank=True, null=True)),
                ('phrase_3', models.TextField(blank=True, null=True)),
                ('synonym_1', models.CharField(blank=True, max_length=100, null=True)),
                ('synonym_2', models.CharField(blank=True, max_length=100, null=True)),
                ('synonym_3', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning_1', models.TextField(blank=True, null=True)),
                ('meaning_2', models.TextField(blank=True, null=True)),
                ('meaning_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
    ]
