# Generated by Django 3.2.2 on 2024-06-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learner_app', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
