# Generated by Django 3.2.2 on 2024-06-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_learner_app', '0003_word_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='annotation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
